# Generated by Django 5.1.3 on 2024-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(verbose_name='desc')),
                ('is_movie', models.BooleanField(default=True, verbose_name='is movie')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('trailer', models.FileField(upload_to='trailers/', verbose_name='trailer')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModel',
            },
        ),
    ]
