# Generated by Django 5.1.3 on 2024-11-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandub', '0003_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'DirectorModel',
                'verbose_name_plural': 'DirectorModel',
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='films-images/', verbose_name='image')),
                ('desc', models.TextField(verbose_name='desc')),
                ('desc_uz', models.TextField(null=True, verbose_name='desc')),
                ('desc_ru', models.TextField(null=True, verbose_name='desc')),
                ('desc_en', models.TextField(null=True, verbose_name='desc')),
                ('year', models.BigIntegerField(verbose_name='year')),
                ('file', models.FileField(upload_to='films/', verbose_name='film')),
                ('category', models.ManyToManyField(to='fandub.categorymodel')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandub.directormodel')),
                ('genre', models.ManyToManyField(to='fandub.genremodel')),
            ],
            options={
                'verbose_name': 'FilmModel',
                'verbose_name_plural': 'FilmModel',
            },
        ),
    ]
